## Exercise 1

![Exercise 1](ex1.svg)

## Exercise 2

![Exercise 2](ex2.svg)

## Exercise 3

(a)
$$\begin{split}
X_1 \perp \!\!\! \perp X_3 | X_2 \\
X_1 \perp \!\!\! \perp X_4 | X_2 \\
X_3 \perp \!\!\! \perp X_4 | X_2 \\
X_1 \perp \!\!\! \perp (X_3, X_4) | X_2 \\
X_3 \perp \!\!\! \perp (X_1, X_4) | X_2 \\
X_4 \perp \!\!\! \perp (X_1, X_3) | X_2 \\
\end{split}$$

(b) 
$$\begin{split}
X_1 \perp \!\!\! \perp X_3 | X_2 \\
X_1 \perp \!\!\! \perp X_4 | X_2 \\
X_1 \perp \!\!\! \perp (X_3, X_4) | X_2 \\
X_1 \perp \!\!\! \perp X_4 | X_3 \\
X_2 \perp \!\!\! \perp X_4 | X_3 \\
(X_1, X_2) \perp \!\!\! \perp X_4 | X_3 \\
\end{split}$$

(c)
$$\begin{split}
X_2 \perp \!\!\! \perp X_4 | X_1, X_3 \\
X_1 \perp \!\!\! \perp X_3 | X_2, X_4 \\
\end{split}$$

(d)
$$\begin{split}
X_1 \perp \!\!\! \perp (X_4, X_5, X_6) | X_2, X_3 \\
X_4 \perp \!\!\! \perp (X_1, X_3, X_6) | X_2, X_5 \\
X_6 \perp \!\!\! \perp (X_1, X_2, X_4) | X_3, X_5 \\
X_4 \perp \!\!\! \perp (X_3, X_6) | X_1, X_2, X_5 \\
X_6 \perp \!\!\! \perp (X_2, X_4) | X_1, X_3, X_5 \\
X_1 \perp \!\!\! \perp (X_5, X_6) | X_2, X_3, X_4 \\
X_1 \perp \!\!\! \perp X_4 | X_2, X_3, X_5 \\
X_1 \perp \!\!\! \perp X_6 | X_2, X_3, X_5 \\
X_4 \perp \!\!\! \perp X_6 | X_2, X_3, X_5 \\
X_1 \perp \!\!\! \perp (X_4, X_6) | X_2, X_3, X_5 \\
X_4 \perp \!\!\! \perp (X_1, X_6) | X_2, X_3, X_5 \\
X_6 \perp \!\!\! \perp (X_1, X_4) | X_2, X_3, X_5 \\
X_1 \perp \!\!\! \perp (X_4, X_6) | X_2, X_3, X_6 \\
X_4 \perp \!\!\! \perp X_6 | X_1, X_2, X_3, X_5 \\
X_3 \perp \!\!\! \perp X_4 | X_1, X_2, X_5, X_6 \\
X_2 \perp \!\!\! \perp X_6 | X_1, X_3, X_4, X_5 \\
X_1 \perp \!\!\! \perp X_6 | X_2, X_3, X_4, X_5 \\
X_1 \perp \!\!\! \perp X_5 | X_2, X_3, X_4, X_6 \\
X_1 \perp \!\!\! \perp X_6 | X_2, X_3, X_4, X_5 \\
X_1 \perp \!\!\! \perp X_4 | X_2, X_3, X_5, X_6 \\
\end{split}$$

## Exercise 4

The unrestricted likelihood for a single observation is given by
$$\mathcal{L}(x_1, x_2, x_3) = p_{000}^{(1-x_1)(1-x_2)(1-x_3)} p_{001}^{(1-x_1)(1-x_2)x_3} p_{010}^{(1-x_1) x_2 (1-x_3)} p_{011}^{(1-x_1)x_2 x_3} p_{100}^{x_1 (1-x_2)(1-x_3)} p_{101}^{x_1 (1-x_2)x_3} p_{110}^{x_1 x_2 (1-x_3)} p_{111}^{x_1 x_2 x_3},$$
where $p_{ijk} = \mathbb{P}(X_1=i, X_2=j, X_3=k)$, thus $\sum_{i,j,k} p_{ijk} = 1$, and so
$$\hat{p}_{ijk} = \frac{1}{n} \sum_{l=1}^n \mathbb{1}_{x_{l,1} = i, x_{l,2} = j, x_{l,3} = k}$$

Under the restricted model $X_1 \perp \!\!\! \perp X_2 | X_3$, we have
$$\mathbb{P}(X_1 = x_1, X_2 = x_2, X_3 = x_3)
= \mathbb{P}(X_1 = x_1, X_2 = x_2 | X_3 = x_3) \mathbb{P}(X_3 = x_3)
= \mathbb{P}(X_1 = x_1 | X_3 = x_3) \mathbb{P}(X_2 = x_2 | X_3 = x_3) \mathbb{P}(X_3 = x_3),$$
so the likelihood for a single observation is given by
$$\begin{split}
\mathcal{L}_0(x_1, x_2, x_3) = 
& (p_{x_1=0|x_3=0} p_{x_2=0|x_3=0} p_{x_3=0})^{(1-x_1)(1-x_2)(1-x_3)} (p_{x_1=0|x_3=1} p_{x_2=0|x_3=1} p_{x_3=1})^{(1-x_1)(1-x_2)x_3}\\
& \times (p_{x_1=0|x_3=0} p_{x_2=1|x_3=0} p_{x_3=0})^{(1-x_1)x_2(1-x_3)} (p_{x_1=0|x_3=1} p_{x_2=1|x_3=1} p_{x_3=1})^{(1-x_1)x_2 x_3} \\
& \times (p_{x_1=1|x_3=0} p_{x_2=0|x_3=0} p_{x_3=0})^{x_1(1-x_2)(1-x_3)} (p_{x_1=1|x_3=1} p_{x_2=0|x_3=1} p_{x_3=1})^{x_1(1-x_2)x_3} \\
& \times (p_{x_1=1|x_3=0} p_{x_2=1|x_3=0} p_{x_3=0})^{x_1 x_2(1-x_3)} (p_{x_1=1|x_3=1} p_{x_2=1|x_3=1} p_{x_3=1})^{x_1 x_2 x_3}, \\
\end{split}$$
so
$$\begin{split}
\log \mathcal{L}_0(x_1, x_2, x_3) = 
& (1-x_1)(1-x_2)(1-x_3)(\log p_{x_1=0|x_3=0} + \log p_{x_2=0|x_3=0} + \log p_{x_3=0}) \\
& + (1-x_1)(1-x_2)x_3 (\log p_{x_1=0|x_3=1} + \log p_{x_2=0|x_3=1} + \log p_{x_3=1}) \\
& + (1-x_1)x_2(1-x_3) (\log p_{x_1=0|x_3=0} + \log p_{x_2=1|x_3=0} + \log p_{x_3=0}) \\
& + (1-x_1)x_2 x_3 (\log p_{x_1=0|x_3=1} + \log p_{x_2=1|x_3=1} + \log p_{x_3=1}) \\
& + x_1(1-x_2)(1-x_3) (\log p_{x_1=1|x_3=0} + \log p_{x_2=0|x_3=0} + \log p_{x_3=0}) \\
& + x_1(1-x_2)x_3 (\log p_{x_1=1|x_3=1} + \log p_{x_2=0|x_3=1} + \log p_{x_3=1}) \\
& + x_1 x_2(1-x_3) (\log p_{x_1=1|x_3=0} + \log p_{x_2=1|x_3=0} + \log p_{x_3=0}) \\
& + x_1 x_2 x_3 (\log p_{x_1=1|x_3=1} + \log p_{x_2=1|x_3=1} + \log p_{x_3=1}) \\
= & (1 - x_3) \log p_{x_3=0} + x_3 \log p_{x_3=1} \\
& + (1 - x_1) (1 - x_3) \log p_{x_1=0|x_3=0} + x_1 (1 - x_3) \log p_{x_1=1|x_3=0} \\
& + (1 - x_1) x_3 \log p_{x_1=0|x_3=1} + x_1 x_3 \log p_{x_1=1|x_3=1} \\
& + (1 - x_2) (1 - x_3) \log p_{x_2=0|x_3=0} + x_2 (1 - x_3) \log p_{x_2=1|x_3=0} \\
& + (1 - x_2) x_3 \log p_{x_2=0|x_3=1} + x_2 x_3 \log p_{x_2=1|x_3=1}. \\
\end{split}$$
Maximising the log-likelihood under the constraints 
$$\begin{split}
& p_{x_3=0} + p_{x_3=1} = 1 \\
& p_{x_1=0|x_3=0} + p_{x_1=1|x_3=0} = 1 \\
& p_{x_1=0|x_3=1} + p_{x_1=1|x_3=1} = 1 \\
\end{split}$$
yields
$$\begin{split}
\hat{p}_{x_3 = 1} &= \frac{1}{n} \sum_{l=1}^n \mathbb{1}_{x_{l,3} = 1} \\
\hat{p}_{x_1=1 | x_3 = 0} &= \frac{\sum_{l=1}^n \mathbb{1}_{x_{l,1} = 1, x_{l,3}=0}}{\sum_{l=1}^n \mathbb{1}_{x_{l,3} = 0}} \\
\hat{p}_{x_1=1 | x_3 = 1} &= \frac{\sum_{l=1}^n \mathbb{1}_{x_{l,1} = 1, x_{l,3}=1}}{\sum_{l=1}^n \mathbb{1}_{x_{l,3} = 1}} \\
\hat{p}_{x_2=1 | x_3 = 0} &= \frac{\sum_{l=1}^n \mathbb{1}_{x_{l,2} = 1, x_{l,3}=0}}{\sum_{l=1}^n \mathbb{1}_{x_{l,3} = 0}} \\
\hat{p}_{x_2=1 | x_3 = 1} &= \frac{\sum_{l=1}^n \mathbb{1}_{x_{l,2} = 1, x_{l,3}=1}}{\sum_{l=1}^n \mathbb{1}_{x_{l,3} = 1}} \\
\end{split}$$

The test statistic for the likelihood ratio test is
$$\lambda = 2 \log \frac{\mathcal{L}}{\mathcal{L}_0}.$$
The unrestricted model has 7 independent parameters, whereas the restricted model has 5 independent parameters, so the likelihood ratio test statistic is asymptotically distributed as $\chi^2_2$.

## Exercise 5

(a) Assuming a multinomial distribution, we have the likelihood
$$\mathcal{L}(p_{1,1,1}, p_{1,1,2}, p_{1,2,1}, p_{1,2,2}, p_{2,1,1}, p_{2,1,2}, p_{2,2,1}, p_{2,2,2})  = {n \choose x_{1,1,1}\; x_{1,1,2}\; x_{1,2,1}\; x_{1,2,2}\; x_{2,1,1}\; x_{2,1,2}\; x_{2,2,1}\; x_{2,2,2}} p_{1,1,1}^{x_{1,1,1}}\; p_{1,1,2}^{x_{1,1,2}}\; p_{1,2,1}^{x_{1,2,1}}\; p_{1,2,2}^{x_{1,2,2}}\; p_{2,1,1}^{x_{2,1,1}}\; p_{2,1,2}^{x_{2,1,2}}\; p_{2,2,1}^{x_{2,2,1}}\; p_{2,2,2}^{x_{2,2,2}},$$
where
$$\begin{split}
p_{1,1,1} &= \mathbb{P}(X_1 = \text{Boston}, X_2 = \text{malignant}, X_3=\text{died}) \\
p_{1,1,2} &= \mathbb{P}(X_1 = \text{Boston}, X_2 = \text{malignant}, X_3=\text{survived}) \\
p_{1,2,1} &= \mathbb{P}(X_1 = \text{Boston}, X_2 = \text{benign}, X_3=\text{died}) \\
p_{1,2,2} &= \mathbb{P}(X_1 = \text{Boston}, X_2 = \text{benign}, X_3=\text{survived}) \\
p_{2,1,1} &= \mathbb{P}(X_1 = \text{Glamorgan}, X_2 = \text{malignant}, X_3=\text{died}) \\
p_{2,1,2} &= \mathbb{P}(X_1 = \text{Glamorgan}, X_2 = \text{malignant}, X_3=\text{survived}) \\
p_{2,2,1} &= \mathbb{P}(X_1 = \text{Glamorgan}, X_2 = \text{benign}, X_3=\text{died}) \\
p_{2,2,2} &= \mathbb{P}(X_1 = \text{Glamorgan}, X_2 = \text{benign}, X_3=\text{survived}) \\
\end{split}$$

In [36]:
import numpy as np
import scipy.stats as stats

In [7]:
x = np.array([
    [
        [35, 59], 
        [47, 112],
    ],
    [
        [42, 77],
        [26, 76],
    ],
])

The maximum likelihood estimator of the probabilities is:

In [73]:
p_hat = x / np.sum(x)
p_hat

array([[[0.07383966, 0.12447257],
        [0.09915612, 0.23628692]],

       [[0.08860759, 0.16244726],
        [0.05485232, 0.16033755]]])

(b) The estimated probability that somebody with a benign tumor at the Glamorgan clinic will die:

In [13]:
p = p_hat[1, 1, 0] / np.sum(p_hat[1, 1])
p

np.float64(0.2549019607843137)

Following section 14.4, the standard error of the estimate is

In [14]:
np.sqrt(p * (1 - p) / np.sum(x))

np.float64(0.02001723683244977)

(c) Using the results of Exercise 4, we test the hypothesis $X_1 \perp \!\!\! \perp X_2 | X_3$.

The probabilities $p_{x_3=\{0,1\}}$:

In [82]:
p3 = np.sum(x, axis=(0, 1), keepdims=True) / np.sum(x)
p3

array([[[0.3164557, 0.6835443]]])

The probabilities $p_{x_1=\{0,1\}|x_3=\{0,1\}}$:

In [83]:
p1 = np.sum(x, axis=1, keepdims=True) / np.sum(x) / p3
p1

array([[[0.54666667, 0.52777778]],

       [[0.45333333, 0.47222222]]])

The probabilities $p_{x_2=\{0,1\}|x_3=\{0,1\}}$:

In [84]:
p2 = np.sum(x, axis=0, keepdims=True) / np.sum(x) / p3
p2

array([[[0.51333333, 0.41975309],
        [0.48666667, 0.58024691]]])

The log-likelihood under unrestricted model:

In [85]:
L1 = np.sum(x * np.log(p_hat))
L1

np.float64(-940.6701829745211)

The log-likelihood under the restricted model:

In [86]:
L0 = np.sum(x * np.log(p1 * p2 * p3))
L0

np.float64(-947.5607811932782)

The test statistics of the likelihood ratio test is:

In [87]:
lam = 2 * (L1 - L0)
lam

np.float64(13.781196437514154)

The p-value is small, so we reject the null hypothesis of conditional independence:

In [88]:
stats.chi2.sf(lam, df=2)

np.float64(0.001017305087944568)

We wrap the test in a function:

In [99]:
def test_cond_independence(x, cond_idx):
    other_idx = tuple(i for i in range(3) if i != cond_idx)
    p_hat = x / np.sum(x)
    p3 = np.sum(x, axis=other_idx, keepdims=True) / np.sum(x)
    p1 = np.sum(x, axis=other_idx[1], keepdims=True) / np.sum(x) / p3
    p2 = np.sum(x, axis=other_idx[0], keepdims=True) / np.sum(x) / p3
    L1 = np.sum(x * np.log(p_hat))
    L0 = np.sum(x * np.log(p1 * p2 * p3))
    lam = 2 * (L1 - L0)
    pvalue = stats.chi2.sf(lam, df=2)
    return lam, pvalue

In [100]:
test_cond_independence(x, 2)

(np.float64(13.781196437514154), np.float64(0.001017305087944568))

Now we test the hypothesis $X_1 \perp \!\!\! \perp X_3 | X_2$:

In [101]:
test_cond_independence(x, 1)

(np.float64(0.600069271822349), np.float64(0.7407925622119846))

We do not reject the null hypothesis of conditional independence.

Finally, we test the hypothesis $X_2 \perp \!\!\! \perp X_3 | X_1$:

In [102]:
test_cond_independence(x, 0)

(np.float64(4.072425016249781), np.float64(0.13052212738006227))

We do not reject the null hypothesis of conditional independence.

The resulting graph is as follows

![Exercise 5](ex5.svg)

The graph suggests that dying ($X_3$) is independent of the type of tumor ($X_2$) and the test location ($X_1$), which does not seem particularly credible.