We replicate the results in Example 19.15.

If $X_1$, $X_2$, $X_3$ are binary, we have for the saturated model
$$\log f = \psi_0 + \psi_1 + \psi_2 + \psi_3 + \psi_{12} + \psi_{13} + \psi_{23} + \psi_{123},$$
where
$$\begin{split}
\psi_0 & = \beta_0 \\
\psi_i & = \beta_i x_i \\
\psi_{ij} & = \beta_{ij} x_i x_j \\
\psi_{ijk} & = \beta_{ijk} x_i x_j x_k \\
\end{split}$$

Since
$$f = p_{000}^{(1-x_1)(1-x_2)(1-x_3)} p_{001}^{(1-x_1)(1-x_2)x_3} p_{010}^{(1-x_1)x_2(1-x_3)} p_{011}^{(1-x_1)x_2 x_3} p_{100}^{x_1(1-x_2)(1-x_3)} p_{101}^{x_1(1-x_2)x_3} p_{110}^{x_1 x_2 (1-x_3)} p_{111}^{x_1 x_2 x_3},
$$
we have
$$\begin{split}
\log f = &(1-x_1)(1-x_2)(1-x_3) \log p_{000} + (1-x_1)(1-x_2)x_3 \log p_{001} + (1-x_1)x_2(1-x_3) \log p_{010} \\
  & + (1-x_1)x_2 x_3 \log p_{011} + x_1(1-x_2)(1-x_3) \log p_{100} + x_1(1-x_2)x_3 \log p_{101} \\
  & + x_1 x_2 (1-x_3) \log p_{110} + x_1 x_2 x_3 \log p_{111} \\
= & \log p_{000} - x_1 \log p_{000} - x_2 \log p_{000} - x_3 \log p_{000} + x_1 x_2 \log p_{000} + x_1 x_3 \log p_{000} + x_2 x_3 \log p_{000} - x_1 x_2 x_3 \log p_{000} \\
  & + x_3 \log p_{001} - x_1 x_3 \log p_{001} - x_2 x_3 \log p_{001} + x_1 x_2 x_3 \log p_{001} \\
  & + x_2 \log p_{010} - x_1 x_2 \log p_{010} - x_2 x_3 \log p_{010} + x_1 x_2 x_3 \log p_{010} \\
  & + x_2 x_3 \log p_{011} - x_1 x_2 x_3 \log p_{011} \\
  & + x_1 \log p_{100} - x_1 x_2 \log p_{100} - x_1 x_3 \log p_{100} + x_1 x_2 x_3 \log p_{100} \\
  & + x_1 x_3 \log p_{101} - x_1 x_2 x_3 \log p_{101} \\
  & + x_1 x_2 \log p_{110} - x_1 x_2 x_3 \log p_{110} \\
  & + x_1 x_2 x_3 \log p_{111} \\
= & \log p_{000} + x_1 \log \frac{p_{100}}{p_{000}} + x_2 \log \frac{p_{010}}{p_{000}} + x_3 \log \frac{p_{001}}{p_{000}} + x_1 x_2 \log \frac{p_{000} p_{110}}{p_{100} p_{010}} + x_1 x_3 \log \frac{p_{000} p_{101}}{p_{100} p_{001}} + x_2 x_3 \log \frac{p_{000} p_{011}}{p_{010} p_{001}} + x_1 x_2 x_3 \log \frac{p_{001} p_{010} p_{100} p_{111}}{p_{000} p_{011} p_{101} p_{110}},
\end{split}$$
that is
$$\begin{split}
\beta_0 &= \log p_{000} \\
\beta_1 &= \log \frac{p_{100}}{p_{000}} \\
\beta_2 &= \log \frac{p_{010}}{p_{000}} \\
\beta_3 &= \log \frac{p_{001}}{p_{000}} \\
\beta_{12} &= \log \frac{p_{000} p_{110}}{p_{100} p_{010}} \\
\beta_{13} &= \log \frac{p_{000} p_{101}}{p_{100} p_{001}} \\
\beta_{23} &= \log \frac{p_{000} p_{011}}{p_{010} p_{001}} \\
\beta_{123} &= \log \frac{p_{001} p_{010} p_{100} p_{111}}{p_{000} p_{011} p_{101} p_{110}} \\
\end{split}$$

Solving these equations for the probabilities, we obtain
$$\begin{split}
p_{000} &= e^{\beta_0} \\
p_{100} &= e^{\beta_0 + \beta_1} \\
p_{010} &= e^{\beta_0 + \beta_2} \\
p_{001} &= e^{\beta_0 + \beta_3} \\
p_{110} &= e^{\beta_0 + \beta_1 + \beta_2 + \beta_{12}} \\
p_{101} &= e^{\beta_0 + \beta_1 + \beta_3 + \beta_{13}} \\
p_{011} &= e^{\beta_0 + \beta_2 + \beta_3 + \beta_{23}} \\
p_{111} &= e^{\beta_0 + \beta_1 + \beta_2 + \beta_3 + \beta_{123}} \\
\end{split}$$

The constraint is $\sum_{i,j,k} p_{ijk} = 1$, which leads to
$$e^{\beta_0} + e^{\beta_0 + \beta_1} + e^{\beta_0 + \beta_2} + e^{\beta_0 + \beta_3} + e^{\beta_0 + \beta_1 + \beta_2 + \beta_{12}} + e^{\beta_0 + \beta_1 + \beta_3 + \beta_{13}} + e^{\beta_0 + \beta_2 + \beta_3 + \beta_{23}} + e^{\beta_0 + \beta_1 + \beta_2 + \beta_3 + \beta_{12} + \beta_{13} + \beta_{23} + \beta_{123}} = 1,$$
so
$$1 + e^{\beta_1} + e^{\beta_2} + e^{\beta_3} + e^{\beta_1 + \beta_2 + \beta_{12}} + e^{\beta_1 + \beta_3 + \beta_{13}} + e^{\beta_2 + \beta_3 + \beta_{23}} + e^{\beta_1 + \beta_2 + \beta_3 + \beta_{12} + \beta_{13} + \beta_{23} + \beta_{123}} = e^{-\beta_0}$$
and
$$\beta_0 = -\log \left(1 + e^{\beta_1} + e^{\beta_2} + e^{\beta_3} + e^{\beta_1 + \beta_2 + \beta_{12}} + e^{\beta_1 + \beta_3 + \beta_{13}} + e^{\beta_2 + \beta_3 + \beta_{23}} + e^{\beta_1 + \beta_2 + \beta_3 + \beta_{12} + \beta_{13} + \beta_{23} + \beta_{123}}\right)$$

The likelihood of a single observation if $f$, so the likelihood of a sample if 
$$\mathcal{L} = \prod_{l=1}^n f(x_l)$$
and the log-likelihood is
$$\log \mathcal{L} = \sum_{l=1}^n \log f(x_l) = \sum_{x^*} \sum_{x_l = x^*} \log f(x^*) = \sum_{x^*} n_{x^*} \log f(x^*),$$
where $x^*$ are distinct possible values of $X$.

In [265]:
import numpy as np
import pandas as pd
import scipy.stats as stats
from scipy.optimize import minimize
import numdifftools as nd

A function to generate indices to select ``k`` elements from an array of size ``d``.

In [64]:
def generate_indices(d, k):
    x = [i for i in range(k)]
    yield tuple(x)
    j = k - 1
    while k > 0:
        # if we cannot advance the last pointer
        if x[j] == d - 1:
            # find the preceding pointer that we can advance
            i = j - 1
            while i >= 0:
                if x[i] < x[i + 1] - 1:
                    break
                i -= 1
            if i < 0:
                # cannot advance any of the pointers
                break
            # update the pointer that can advance
            x[i] += 1
            # set all subsequent pointers
            for j in range(i + 1, k):
                x[j] = x[i] + j - i
        else:
            x[j] += 1
        yield tuple(x)

In [43]:
list(generate_indices(5, 2))

[(0, 1),
 (0, 2),
 (0, 3),
 (0, 4),
 (1, 2),
 (1, 3),
 (1, 4),
 (2, 3),
 (2, 4),
 (3, 4)]

A function to check if a model is hierarchical:

In [160]:
def is_hierarchical(betas_included):
    d = len(betas_included)
    all_indices = [list(generate_indices(d, k)) for k in range(1, d + 1)]
    for k in range(d):
        for i, beta_included in enumerate(betas_included[k]):
            if not beta_included:
                for l in range(k + 1, d):
                    for j, higher_dim_beta_included in enumerate(betas_included[l]):
                        if higher_dim_beta_included and set(all_indices[k][i]).issubset(all_indices[l][j]):
                            return False
    return True

A model is encoded as a list of tuples for combinations of each dimension, for example ``[(True, True, True), (False, True, True), (False,)]`` encodes a model that has non-zero $\psi_0$, $\psi_1$, $\psi_2$, $\psi_3$, $\psi_{13}$, $\psi_{23}$ and zero $\psi_{12}$, $\psi_{123}$, which is hierarchical. The order of flags in each group corresponds to the order generated by ``generate_indices`` for the given number of elements.

In [161]:
is_hierarchical([(True, True, True), (False, True, True), (False,)])

True

In [162]:
is_hierarchical([(True, True, False), (False, False, True), (False,)])

False

A function to calculate the value of
$$e^{\beta_1} + e^{\beta_2} + e^{\beta_3} + e^{\beta_1 + \beta_2 + \beta_{12}} + e^{\beta_1 + \beta_3 + \beta_{13}} + e^{\beta_2 + \beta_3 + \beta_{23}} + e^{\beta_1 + \beta_2 + \beta_3 + \beta_{12} + \beta_{13} + \beta_{23} + \beta_{123}}$$

In [202]:
def calculate_beta_exp(betas, betas_included):
    n_betas = sum(sum(v) for v in betas_included)
    assert n_betas == len(betas)
    d = len(betas_included)
    all_indices = [list(generate_indices(d, k)) for k in range(1, d + 1)]
    res = 0
    beta_idx = 0
    for k, betas_group in enumerate(betas_included):
        for j, beta_included in enumerate(betas_group):
            beta_exp = 0
            if beta_included:
                beta_exp += betas[beta_idx]
                beta_idx += 1
            beta_idx2 = 0
            for k2 in range(k):
                for j2, lower_dim_beta_included in enumerate(betas_included[k2]):
                    if lower_dim_beta_included:
                        if set(all_indices[k2][j2]).issubset(all_indices[k][j]):
                            beta_exp += betas[beta_idx2]
                        beta_idx2 += 1
            res += np.exp(beta_exp)
    return res

In [220]:
def calculate_beta0(betas, betas_included):
    return -np.log(1 + calculate_beta_exp(betas, betas_included))

A function to calculate $\log f$ given the values of $\beta$ and the model specification:

In [221]:
def calculate_log_f(betas, betas_included):
    n_betas = sum(sum(v) for v in betas_included)
    assert n_betas == len(betas)
    d = len(betas_included)
    res = np.zeros((2,) * d)
    SLICE_ALL = slice(None, None, None)
    all_indices = [list(generate_indices(d, k)) for k in range(1, d + 1)]
    beta_idx = 0
    for k, betas_group in enumerate(betas_included):
        for j, beta_included in enumerate(betas_group):
            if beta_included:
                multi_idx = tuple([1 if i in all_indices[k][j] else SLICE_ALL for i in range(d)])
                res[multi_idx] += betas[beta_idx]
                beta_idx += 1
    res += calculate_beta0(betas, betas_included)
    return res

A function to calculate the log-likelihood for a given sample:

In [222]:
def log_lik(x, betas, betas_included):
    return np.sum(x * calculate_log_f(betas, betas_included))

In [223]:
x = np.array([
    [
        [35, 59],
        [47, 112],
    ],
    [
        [42, 77],
        [26, 76],
    ],
])

In [224]:
betas_included = [(True, True, True), (True, True, True), (True,)]

In [225]:
assert is_hierarchical(betas_included)

In [293]:
def objective(beta):
    return -log_lik(x, beta, betas_included)

In [294]:
n_betas = sum(sum(v) for v in betas_included)

In [295]:
res = minimize(objective, np.repeat(0.1, n_betas))
res

  message: Optimization terminated successfully.
  success: True
   status: 0
      fun: 940.6701829745268
        x: [ 1.823e-01  2.948e-01  5.222e-01 -7.744e-01  8.395e-02
             3.462e-01  1.203e-01]
      nit: 18
      jac: [ 0.000e+00  0.000e+00  0.000e+00  7.629e-06  7.629e-06
            -7.629e-06  0.000e+00]
 hess_inv: [[ 1.348e-02 -1.083e-03 ...  4.175e-03 -5.254e-05]
            [-1.083e-03  3.542e-02 ... -2.670e-02  1.207e-05]
            ...
            [ 4.175e-03 -2.670e-02 ...  4.055e-02 -1.080e-02]
            [-5.254e-05  1.207e-05 ... -1.080e-02  5.575e-02]]
     nfev: 168
     njev: 21

In [262]:
h = nd.Hessian(objective)
se = np.sqrt(np.diag(np.linalg.inv(h(res.x))))

In [269]:
pd.DataFrame({
    'beta': res.x,
    'se': se,
    'W': res.x / se,
    'p-value': 2 * stats.norm.sf(np.abs(res.x) / se),
})

beta        se         W   p-value
0  0.182321  0.228869  0.796617  0.425673
1  0.294799  0.223267  1.320390  0.186705
2  0.522189  0.213355  2.447507  0.014385
3 -0.774372  0.334842 -2.312650  0.020742
4  0.083947  0.286910  0.292591  0.769835
5  0.346162  0.275183  1.257934  0.208416
6  0.120338  0.405144  0.297026  0.766447

In [268]:
calculate_beta0(res.x, betas_included)

np.float64(-2.6058588558268623)

The procedure used in the book (see ``example19.15.R``) fits a regression model
$$\log y = \beta_0 + \beta_1 x_1 + \beta_2 x_2 + \beta_3 x_3 + \beta_{12} x_1 x_2 + \beta_{13} x_1 x_3 + \beta_{23} x_2 x_3 + \beta_{123} x_1 x_2 x_3,$$
so the intercept is $\log 35 = 3.56$ (35 is the value of $y$ where $x_1 = x_2 = x_3 = 0$).